language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  #- zip -r ray_proj *
  #- mkdir -p deploy
  #- mv ray_proj.zip deploy/ray_proj.zip
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/ray_proj.zip


deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:  $AWS_SECRET_KEY
  bucket: ray-proj-build
  region: ap-northeast-2
  skip_cleanup: true
  acl: private
  local_dir: deploy
  wait-until-deployed: true

- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:  $AWS_SECRET_KEY
  bucket: ray-proj-build
  key: ray_proj.zip
  bundle_type: zip
  application: ray_proj
  deployment_group: ray_proj_group
  region: ap-northeast-2
  wait-until-deployed: true

#CI 실행완료 시 메일로 알람
notifications:
  email:
    recipients:
      - chosh1614@gmail.com


